eureka:
  client:
    register-with-eureka: true

server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: rol-microservice
          uri: http://localhost:3001
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/api/rol/**,
        - id: church-microservice
          uri: http://localhost:3002
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/api/church/**,
        - id: team-pesca-microservice
          uri: http://localhost:3003
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/api/team_pesca/**

        - id: ministerial-microservice
          uri: http://localhost:3004
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/api/ministerial/**,





        - id: user-microservice
          uri: http://localhost:3006
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/api/user/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG